import type { ErpReportSnapshot } from "../../../types/domain.js";

function formatDisplayDate(value: string | Date): string {
  const rawValue = value == null ? "" : String(value);
  if (!rawValue) return "";

  const date =
    value instanceof Date
      ? value
      : rawValue.length === 10 && /^\d{4}-\d{2}-\d{2}$/.test(rawValue)
        ? new Date(`${rawValue}T00:00:00Z`)
        : new Date(rawValue);

  if (Number.isNaN(date.getTime())) {
    return rawValue;
  }

  return new Intl.DateTimeFormat("en-KE", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    timeZone: "Africa/Nairobi",
  }).format(date);
}

function formatMoney(value: number): string {
  return `KES ${value.toLocaleString("en-KE", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

export function formatReportWhatsApp(snapshot: ErpReportSnapshot): {
  text: string;
} {
  const { data, periodType, periodStart, periodEnd } = snapshot;

  const label = periodType === "DAILY" ? "Daily" : "Weekly";

  const start = formatDisplayDate(periodStart as string | Date);
  const end = formatDisplayDate(periodEnd as string | Date);

  const stockStatus =
    data.lowStockCount > 0
      ? [
          `⚠️ *Stock Alert*`,
          `${data.lowStockCount} ${
            data.lowStockCount === 1 ? "item is" : "items are"
          } currently running low.`,
          `👉 Review inventory and consider restocking.`,
        ].join("\n")
      : [`✅ *Inventory Status*`, `Stock levels are currently healthy.`].join(
          "\n",
        );

  const text = [
    `📊 *ERPKE BUSINESS REPORT*`,
    `_${label} Performance Summary_`,
    ``,
    `📅 *${start} → ${end}*`,
    `🕐 East Africa Time (EAT)`,
    ``,
    `━━━━━━━━━━━━━━━━━━━━`,
    `💰 *SALES PERFORMANCE*`,
    `━━━━━━━━━━━━━━━━━━━━`,
    ``,
    `💵 *Sales Value*`,
    `   ${formatMoney(data.salesValue)}`,
    ``,
    `━━━━━━━━━━━━━━━━━━━━`,
    `🧾 *FINANCIAL POSITION*`,
    `━━━━━━━━━━━━━━━━━━━━`,
    ``,
    `💳 *Outstanding Invoices*`,
    `   ${formatMoney(data.outstandingInvoices)}`,
    ``,
    `━━━━━━━━━━━━━━━━━━━━`,
    `📦 *INVENTORY POSITION*`,
    `━━━━━━━━━━━━━━━━━━━━`,
    ``,
    `🏷️ *Stock Value*`,
    `   ${formatMoney(data.stockValue)}`,
    ``,
    `━━━━━━━━━━━━━━━━━━━━`,
    ``,
    stockStatus,
    ``,
    `━━━━━━━━━━━━━━━━━━━━`,
    `📌 *REPORT SUMMARY*`,
    ``,
    `Sales: *${formatMoney(data.salesValue)}*`,
    `Orders: *${data.ordersCount}*`,
    `Receivables: *${formatMoney(data.outstandingInvoices)}*`,
    `Inventory: *${formatMoney(data.stockValue)}*`,
    ``,
    `🤖 _Automatically generated by ERPKE_`,
    `_Business management made simple._`,
  ].join("\n");

  return { text };
}
