-- ============================================================
-- 001_access.sql
-- ERP authorization and access management
--
-- IAS remains responsible for:
--   - users
--   - companies
--   - authentication
--   - system/product roles
--
-- ERP is responsible for:
--   - ERP roles
--   - ERP permissions
--   - role assignments
--   - approval limits
--   - approval delegation
-- ============================================================


-- ------------------------------------------------------------
-- ERP roles
--
-- Roles are company-specific.
-- Therefore (ias_company_id, id) must be unique so other tables
-- can enforce tenant-safe foreign keys.
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT NOT NULL,

  name VARCHAR(100) NOT NULL,
  code VARCHAR(50) NOT NULL,

  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Company-specific role code
  UNIQUE (ias_company_id, code),

  -- Required for composite foreign keys
  UNIQUE (ias_company_id, id)
);


-- ------------------------------------------------------------
-- Permission catalog
--
-- Permissions are GLOBAL.
--
-- Example:
--   inventory:view
--   inventory:adjust_stock
--   finance:view
--
-- They are not owned by a company.
-- A company gets these permissions by assigning them to
-- its own ERP roles.
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  module VARCHAR(50) NOT NULL,
  action VARCHAR(50) NOT NULL,

  code VARCHAR(120)
    GENERATED ALWAYS AS (module || ':' || action) STORED,

  UNIQUE (module, action)
);


-- ------------------------------------------------------------
-- Role → permission
--
-- No ias_company_id required here because:
--
--   erp_roles          = company-specific
--   erp_permissions    = global
--
-- The role determines the company.
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_role_permissions (
  role_id BIGINT NOT NULL
    REFERENCES erp_roles(id)
    ON DELETE CASCADE,

  permission_id BIGINT NOT NULL
    REFERENCES erp_permissions(id)
    ON DELETE CASCADE,

  PRIMARY KEY (role_id, permission_id)
);


-- ------------------------------------------------------------
-- User → role assignment
--
-- IMPORTANT:
-- role_id must belong to the SAME company as ias_company_id.
--
-- This prevents:
--
-- Company A user
--      ↓
-- Company B role
--
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_role_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_user_id BIGINT NOT NULL,
  ias_company_id BIGINT NOT NULL,

  role_id BIGINT NOT NULL,

  branch_id BIGINT,

  assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  assigned_by BIGINT,

  UNIQUE (
    ias_user_id,
    ias_company_id,
    role_id,
    branch_id
  ),

  -- Tenant-safe role relationship
  CONSTRAINT fk_role_assignment_role
    FOREIGN KEY (ias_company_id, role_id)
    REFERENCES erp_roles (ias_company_id, id)
    ON DELETE CASCADE
);


CREATE INDEX IF NOT EXISTS idx_role_assignments_company
  ON erp_role_assignments(ias_company_id);

CREATE INDEX IF NOT EXISTS idx_role_assignments_user
  ON erp_role_assignments(ias_company_id, ias_user_id);

CREATE INDEX IF NOT EXISTS idx_role_assignments_role
  ON erp_role_assignments(ias_company_id, role_id);


-- ------------------------------------------------------------
-- Approval limits
--
-- These are directly owned by a company + IAS user.
-- There is no ERP-owned parent table to reference.
--
-- Therefore no composite FK is required here.
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_approval_limits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_user_id BIGINT NOT NULL,
  ias_company_id BIGINT NOT NULL,

  module VARCHAR(50) NOT NULL,

  max_amount NUMERIC(14,2) NOT NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'KES',

  UNIQUE (
    ias_user_id,
    ias_company_id,
    module
  ),

  CHECK (max_amount >= 0)
);


CREATE INDEX IF NOT EXISTS idx_approval_limits_company
  ON erp_approval_limits(ias_company_id);

CREATE INDEX IF NOT EXISTS idx_approval_limits_user
  ON erp_approval_limits(ias_company_id, ias_user_id);


-- ------------------------------------------------------------
-- Approval delegations
--
-- from_user_id and to_user_id belong to IAS.
-- We intentionally don't create local FK constraints because
-- IAS owns the users.
--
-- Both users are scoped by ias_company_id at the application
-- and service layer.
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_approval_delegations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  from_user_id BIGINT NOT NULL,
  to_user_id BIGINT NOT NULL,

  ias_company_id BIGINT NOT NULL,

  module VARCHAR(50),

  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CHECK (from_user_id <> to_user_id),
  CHECK (ends_at > starts_at)
);


CREATE INDEX IF NOT EXISTS idx_approval_delegations_company
  ON erp_approval_delegations(ias_company_id);

CREATE INDEX IF NOT EXISTS idx_approval_delegations_from_user
  ON erp_approval_delegations(ias_company_id, from_user_id);

CREATE INDEX IF NOT EXISTS idx_approval_delegations_to_user
  ON erp_approval_delegations(ias_company_id, to_user_id);


-- ------------------------------------------------------------
-- Audit log
--
-- Audit records are already directly scoped to a company.
--
-- entity_id is intentionally generic because the entity can be:
--   invoice
--   payment
--   purchase_order
--   employee
--   stock_movement
--   etc.
--
-- We don't create FKs here because entity_id can reference
-- different tables depending on entity_type.
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_user_id BIGINT NOT NULL,
  ias_company_id BIGINT NOT NULL,

  entity_type VARCHAR(50) NOT NULL,
  entity_id BIGINT NOT NULL,

  action VARCHAR(50) NOT NULL,

  before_state JSONB,
  after_state JSONB,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE INDEX IF NOT EXISTS idx_audit_entity
  ON erp_audit_log(entity_type, entity_id);

CREATE INDEX IF NOT EXISTS idx_audit_company
  ON erp_audit_log(ias_company_id);

CREATE INDEX IF NOT EXISTS idx_audit_user
  ON erp_audit_log(ias_company_id, ias_user_id);


-- ------------------------------------------------------------
-- Provisioning events
--
-- These belong to a company/user combination but reference
-- IAS-owned entities, so no local FK is required.
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_provisioning_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT,
  ias_user_id BIGINT,

  event_type VARCHAR(50) NOT NULL,

  processed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (
    ias_company_id,
    ias_user_id,
    event_type
  )
);


CREATE INDEX IF NOT EXISTS idx_provisioning_events_company
  ON erp_provisioning_events(ias_company_id);