-- ============================================================
-- 001_access.sql
-- ERP authorization and access management
--
-- IAS remains responsible for:
--   - users
--   - companies
--   - authentication
--   - system/product roles
--
-- ERP is responsible for:
--   - ERP roles
--   - ERP permissions
--   - role assignments
--   - approval limits
--   - approval delegation
-- ============================================================


-- ------------------------------------------------------------
-- ERP roles
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ias_company_id BIGINT NOT NULL,
  name VARCHAR(100) NOT NULL,
  code VARCHAR(50) NOT NULL,

  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (ias_company_id, code)
);


-- ------------------------------------------------------------
-- Permission catalog
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  module VARCHAR(50) NOT NULL,
  action VARCHAR(50) NOT NULL,

  code VARCHAR(120)
    GENERATED ALWAYS AS (module || ':' || action) STORED,

  UNIQUE (module, action)
);


-- ------------------------------------------------------------
-- Role → permission
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_role_permissions (
  role_id BIGINT NOT NULL
    REFERENCES erp_roles(id)
    ON DELETE CASCADE,

  permission_id BIGINT NOT NULL
    REFERENCES erp_permissions(id)
    ON DELETE CASCADE,

  PRIMARY KEY (role_id, permission_id)
);


-- ------------------------------------------------------------
-- User → role assignment
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_role_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_user_id BIGINT NOT NULL,
  ias_company_id BIGINT NOT NULL,

  role_id BIGINT NOT NULL
    REFERENCES erp_roles(id)
    ON DELETE CASCADE,

  branch_id BIGINT,

  assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  assigned_by BIGINT,

  UNIQUE (
    ias_user_id,
    ias_company_id,
    role_id,
    branch_id
  )
);


-- ------------------------------------------------------------
-- Approval limits
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_approval_limits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_user_id BIGINT NOT NULL,
  ias_company_id BIGINT NOT NULL,

  module VARCHAR(50) NOT NULL,

  max_amount NUMERIC(14,2) NOT NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'KES',

  UNIQUE (
    ias_user_id,
    ias_company_id,
    module
  ),

  CHECK (max_amount >= 0)
);


-- ------------------------------------------------------------
-- Approval delegations
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_approval_delegations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  from_user_id BIGINT NOT NULL,
  to_user_id BIGINT NOT NULL,
  ias_company_id BIGINT NOT NULL,

  module VARCHAR(50),

  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CHECK (from_user_id <> to_user_id),
  CHECK (ends_at > starts_at)
);


CREATE INDEX IF NOT EXISTS idx_approval_delegations_company
  ON erp_approval_delegations(ias_company_id);


-- ------------------------------------------------------------
-- Audit log
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_user_id BIGINT NOT NULL,
  ias_company_id BIGINT NOT NULL,

  entity_type VARCHAR(50) NOT NULL,
  entity_id BIGINT NOT NULL,

  action VARCHAR(50) NOT NULL,

  before_state JSONB,
  after_state JSONB,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_entity
  ON erp_audit_log(entity_type, entity_id);

CREATE INDEX IF NOT EXISTS idx_audit_company
  ON erp_audit_log(ias_company_id);

CREATE INDEX IF NOT EXISTS idx_audit_user
  ON erp_audit_log(ias_user_id, ias_company_id);


-- ------------------------------------------------------------
-- Provisioning events
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_provisioning_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT,
  ias_user_id BIGINT,

  event_type VARCHAR(50) NOT NULL,

  processed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (
    ias_company_id,
    ias_user_id,
    event_type
  )
);