-- ============================================================
-- 002_organization.sql
-- Company organizational structures
-- ============================================================


-- ------------------------------------------------------------
-- Branches
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_branches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ias_company_id BIGINT NOT NULL,
  name VARCHAR(100) NOT NULL,
  code VARCHAR(50) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (ias_company_id, code)
);


CREATE INDEX IF NOT EXISTS idx_branches_company
  ON erp_branches(ias_company_id);


-- ------------------------------------------------------------
-- Add branch relationship to role assignments
-- ------------------------------------------------------------

ALTER TABLE erp_role_assignments
  ADD CONSTRAINT fk_role_assignment_branch
  FOREIGN KEY (branch_id)
  REFERENCES erp_branches(id)
  ON DELETE SET NULL;