-- ERP Phase 2+ schema: Sales, Purchasing, CRM-lite, Finance, HR, Reporting and Workflow.
-- All business rows are scoped by ias_company_id.

-- CRM / Contacts
CREATE TABLE IF NOT EXISTS erp_contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ias_company_id BIGINT NOT NULL,
  contact_type VARCHAR(20) NOT NULL DEFAULT 'CUSTOMER',
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(50), email VARCHAR(255), address TEXT, tax_id VARCHAR(100),
  credit_limit NUMERIC(15,2) NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (contact_type IN ('CUSTOMER','SUPPLIER','BOTH')),
  UNIQUE (ias_company_id, name, contact_type)
);
CREATE INDEX IF NOT EXISTS idx_contacts_company ON erp_contacts(ias_company_id);

CREATE TABLE IF NOT EXISTS erp_contact_interactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ias_company_id BIGINT NOT NULL, contact_id BIGINT NOT NULL REFERENCES erp_contacts(id) ON DELETE CASCADE,
  interaction_type VARCHAR(30) NOT NULL, notes TEXT, occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_contact_interactions ON erp_contact_interactions(ias_company_id, contact_id);

-- Sales
CREATE TABLE IF NOT EXISTS erp_sales_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ias_company_id BIGINT NOT NULL, order_number VARCHAR(50) NOT NULL,
  customer_id BIGINT NOT NULL REFERENCES erp_contacts(id),
  warehouse_id BIGINT NOT NULL REFERENCES erp_warehouses(id),
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  order_date TIMESTAMPTZ NOT NULL DEFAULT now(),
  currency VARCHAR(10) NOT NULL DEFAULT 'KES',
  subtotal NUMERIC(15,2) NOT NULL DEFAULT 0, discount_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
  tax_amount NUMERIC(15,2) NOT NULL DEFAULT 0, total_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
  notes TEXT, created_by BIGINT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(ias_company_id, order_number)
);
CREATE INDEX IF NOT EXISTS idx_sales_orders_company_status ON erp_sales_orders(ias_company_id,status);
CREATE TABLE IF NOT EXISTS erp_sales_order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sales_order_id BIGINT NOT NULL REFERENCES erp_sales_orders(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES erp_products(id),
  product_sku VARCHAR(100) NOT NULL, product_name VARCHAR(255) NOT NULL,
  quantity NUMERIC(15,3) NOT NULL, unit_price NUMERIC(15,2) NOT NULL,
  discount_amount NUMERIC(15,2) NOT NULL DEFAULT 0, tax_rate NUMERIC(7,4) NOT NULL DEFAULT 0,
  line_total NUMERIC(15,2) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sales_items_order ON erp_sales_order_items(sales_order_id);

-- Finance
CREATE TABLE IF NOT EXISTS erp_invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ias_company_id BIGINT NOT NULL, invoice_number VARCHAR(50) NOT NULL,
  customer_id BIGINT NOT NULL REFERENCES erp_contacts(id),
  sales_order_id BIGINT REFERENCES erp_sales_orders(id),
  status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
  issue_date DATE NOT NULL DEFAULT CURRENT_DATE, due_date DATE,
  currency VARCHAR(10) NOT NULL DEFAULT 'KES',
  subtotal NUMERIC(15,2) NOT NULL DEFAULT 0, tax_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
  total_amount NUMERIC(15,2) NOT NULL DEFAULT 0, paid_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
  notes TEXT, created_by BIGINT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(ias_company_id, invoice_number)
);
CREATE INDEX IF NOT EXISTS idx_invoices_ar ON erp_invoices(ias_company_id,status,customer_id);
CREATE TABLE IF NOT EXISTS erp_invoice_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id BIGINT NOT NULL REFERENCES erp_invoices(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES erp_products(id), product_sku VARCHAR(100), product_name VARCHAR(255) NOT NULL,
  quantity NUMERIC(15,3) NOT NULL, unit_price NUMERIC(15,2) NOT NULL,
  tax_rate NUMERIC(7,4) NOT NULL DEFAULT 0, line_total NUMERIC(15,2) NOT NULL
);
CREATE TABLE IF NOT EXISTS erp_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ias_company_id BIGINT NOT NULL, customer_id BIGINT REFERENCES erp_contacts(id),
  payment_reference VARCHAR(100) NOT NULL, amount NUMERIC(15,2) NOT NULL,
  payment_date DATE NOT NULL DEFAULT CURRENT_DATE, method VARCHAR(30) NOT NULL DEFAULT 'CASH',
  notes TEXT, created_by BIGINT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(ias_company_id,payment_reference)
);
CREATE TABLE IF NOT EXISTS erp_payment_allocations (
  payment_id BIGINT NOT NULL REFERENCES erp_payments(id) ON DELETE CASCADE,
  invoice_id BIGINT NOT NULL REFERENCES erp_invoices(id) ON DELETE CASCADE,
  amount NUMERIC(15,2) NOT NULL, PRIMARY KEY(payment_id,invoice_id)
);
CREATE TABLE IF NOT EXISTS erp_journal_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ias_company_id BIGINT NOT NULL, reference_type VARCHAR(50), reference_id BIGINT,
  description TEXT NOT NULL, entry_date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_by BIGINT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS erp_journal_lines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  journal_entry_id BIGINT NOT NULL REFERENCES erp_journal_entries(id) ON DELETE CASCADE,
  account_code VARCHAR(50) NOT NULL, debit NUMERIC(15,2) NOT NULL DEFAULT 0, credit NUMERIC(15,2) NOT NULL DEFAULT 0
);

-- Purchasing
CREATE TABLE IF NOT EXISTS erp_purchase_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ias_company_id BIGINT NOT NULL, po_number VARCHAR(50) NOT NULL,
  supplier_id BIGINT NOT NULL REFERENCES erp_contacts(id), warehouse_id BIGINT NOT NULL REFERENCES erp_warehouses(id),
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT', order_date TIMESTAMPTZ NOT NULL DEFAULT now(),
  expected_date DATE, currency VARCHAR(10) NOT NULL DEFAULT 'KES',
  subtotal NUMERIC(15,2) NOT NULL DEFAULT 0, tax_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
  total_amount NUMERIC(15,2) NOT NULL DEFAULT 0, notes TEXT, created_by BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(ias_company_id,po_number)
);
CREATE TABLE IF NOT EXISTS erp_purchase_order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_order_id BIGINT NOT NULL REFERENCES erp_purchase_orders(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES erp_products(id), product_sku VARCHAR(100) NOT NULL,
  product_name VARCHAR(255) NOT NULL, quantity NUMERIC(15,3) NOT NULL, received_quantity NUMERIC(15,3) NOT NULL DEFAULT 0,
  unit_cost NUMERIC(15,2) NOT NULL, tax_rate NUMERIC(7,4) NOT NULL DEFAULT 0, line_total NUMERIC(15,2) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_po_company_status ON erp_purchase_orders(ias_company_id,status);

-- HR
CREATE TABLE IF NOT EXISTS erp_employees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ias_company_id BIGINT NOT NULL, employee_number VARCHAR(50) NOT NULL,
  first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, email VARCHAR(255),
  phone VARCHAR(50), department VARCHAR(100), job_title VARCHAR(100),
  hire_date DATE, salary NUMERIC(15,2) NOT NULL DEFAULT 0, status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(ias_company_id,employee_number)
);
CREATE TABLE IF NOT EXISTS erp_attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ias_company_id BIGINT NOT NULL, employee_id BIGINT NOT NULL REFERENCES erp_employees(id) ON DELETE CASCADE,
  attendance_date DATE NOT NULL, clock_in TIMESTAMPTZ, clock_out TIMESTAMPTZ, notes TEXT,
  UNIQUE(ias_company_id,employee_id,attendance_date)
);
CREATE TABLE IF NOT EXISTS erp_leave_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ias_company_id BIGINT NOT NULL, employee_id BIGINT NOT NULL REFERENCES erp_employees(id) ON DELETE CASCADE,
  leave_type VARCHAR(50) NOT NULL, starts_on DATE NOT NULL, ends_on DATE NOT NULL,
  reason TEXT, status VARCHAR(20) NOT NULL DEFAULT 'PENDING', approved_by BIGINT, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS erp_payroll_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ias_company_id BIGINT NOT NULL, period_start DATE NOT NULL, period_end DATE NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT', total_gross NUMERIC(15,2) NOT NULL DEFAULT 0,
  total_deductions NUMERIC(15,2) NOT NULL DEFAULT 0, total_net NUMERIC(15,2) NOT NULL DEFAULT 0,
  created_by BIGINT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(ias_company_id,period_start,period_end)
);
CREATE TABLE IF NOT EXISTS erp_payroll_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payroll_run_id BIGINT NOT NULL REFERENCES erp_payroll_runs(id) ON DELETE CASCADE,
  employee_id BIGINT NOT NULL REFERENCES erp_employees(id), gross NUMERIC(15,2) NOT NULL,
  deductions NUMERIC(15,2) NOT NULL DEFAULT 0, net NUMERIC(15,2) NOT NULL
);

-- Notifications / workflow
CREATE TABLE IF NOT EXISTS erp_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ias_company_id BIGINT NOT NULL, ias_user_id BIGINT,
  type VARCHAR(50) NOT NULL, title VARCHAR(255) NOT NULL, message TEXT NOT NULL,
  entity_type VARCHAR(50), entity_id BIGINT, is_read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON erp_notifications(ias_company_id,ias_user_id,is_read);
CREATE TABLE IF NOT EXISTS erp_workflow_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ias_company_id BIGINT NOT NULL, name VARCHAR(255) NOT NULL,
  event_type VARCHAR(100) NOT NULL, threshold_amount NUMERIC(15,2),
  action_type VARCHAR(50) NOT NULL DEFAULT 'NOTIFY', target_user_id BIGINT, status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_by BIGINT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS erp_approval_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ias_company_id BIGINT NOT NULL, module VARCHAR(50) NOT NULL, entity_type VARCHAR(50) NOT NULL,
  entity_id BIGINT NOT NULL, requested_by BIGINT NOT NULL, assigned_to BIGINT,
  amount NUMERIC(15,2), status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  decided_by BIGINT, decided_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Permissions
INSERT INTO erp_permissions(module,action) VALUES
 ('sales','manage_orders'),('sales','approve_order'),('sales','ship_order'),('sales','create_invoice'),
 ('purchasing','manage_po'),('purchasing','receive_goods'),('purchasing','approve_po'),
 ('crm','view'),('crm','manage_contacts'),('crm','log_interaction'),
 ('finance','manage_invoices'),('finance','post_payment'),('finance','view_reports'),('finance','post_journal'),
 ('hr','manage_employees'),('hr','manage_attendance'),('hr','approve_leave'),('hr','run_payroll'),
 ('reporting','view'),('reporting','export'),('workflow','manage_rules'),('workflow','manage_approvals')
ON CONFLICT(module,action) DO NOTHING;
