-- ============================================================
-- 003_inventory.sql
-- Inventory, warehouses, products and stock ledger
-- ============================================================


-- ------------------------------------------------------------
-- Warehouses
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_warehouses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT NOT NULL,

  code VARCHAR(50) NOT NULL,
  name VARCHAR(255) NOT NULL,
  location VARCHAR(255),

  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (ias_company_id, code)
);


CREATE INDEX IF NOT EXISTS idx_warehouses_company
  ON erp_warehouses(ias_company_id);


-- ------------------------------------------------------------
-- Products
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT NOT NULL,

  sku VARCHAR(100) NOT NULL,
  name VARCHAR(255) NOT NULL,

  description TEXT,

  unit VARCHAR(50) NOT NULL DEFAULT 'pcs',
  category VARCHAR(100),

  cost_price NUMERIC(15,2) NOT NULL DEFAULT 0,
  sell_price NUMERIC(15,2) NOT NULL DEFAULT 0,

  reorder_level NUMERIC(15,3) NOT NULL DEFAULT 0,

  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (ias_company_id, sku),

  CHECK (cost_price >= 0),
  CHECK (sell_price >= 0),
  CHECK (reorder_level >= 0)
);


CREATE INDEX IF NOT EXISTS idx_products_company
  ON erp_products(ias_company_id);


-- ------------------------------------------------------------
-- Stock levels
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_stock_levels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Tenant/company ownership
  ias_company_id BIGINT NOT NULL,

  -- Product
  product_id BIGINT NOT NULL,
  product_sku VARCHAR(100) NOT NULL,
  product_name VARCHAR(255) NOT NULL,

  -- Warehouse
  warehouse_id BIGINT NOT NULL,
  warehouse_name VARCHAR(255) NOT NULL,

  -- Stock quantities
  quantity NUMERIC(15,3) NOT NULL DEFAULT 0,
  reserved_quantity NUMERIC(15,3) NOT NULL DEFAULT 0,

  -- Weighted average cost
  average_cost NUMERIC(15,2) NOT NULL DEFAULT 0,

  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Prevent duplicate stock record for the same product/warehouse
  UNIQUE (product_id, warehouse_id),

  -- Make (company, id) available for tenant-aware foreign keys
  CONSTRAINT uq_stock_levels_company_id
    UNIQUE (ias_company_id, id),

  -- Product must belong to the same company
  CONSTRAINT fk_stock_levels_product
    FOREIGN KEY (ias_company_id, product_id)
    REFERENCES erp_products (ias_company_id, id)
    ON DELETE CASCADE,

  -- Warehouse must belong to the same company
  CONSTRAINT fk_stock_levels_warehouse
    FOREIGN KEY (ias_company_id, warehouse_id)
    REFERENCES erp_warehouses (ias_company_id, id)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_stock_levels_company
  ON erp_stock_levels (ias_company_id);

CREATE INDEX IF NOT EXISTS idx_stock_levels_product
  ON erp_stock_levels (ias_company_id, product_id);

CREATE INDEX IF NOT EXISTS idx_stock_levels_warehouse
  ON erp_stock_levels (ias_company_id, warehouse_id);

-- ------------------------------------------------------------
-- Stock movements
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_stock_movements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT NOT NULL,

  product_id BIGINT NOT NULL
    REFERENCES erp_products(id)
    ON DELETE CASCADE,

  product_sku VARCHAR(100) NOT NULL,
  product_name VARCHAR(255) NOT NULL,

  warehouse_id BIGINT NOT NULL
    REFERENCES erp_warehouses(id)
    ON DELETE CASCADE,

  warehouse_name VARCHAR(255) NOT NULL,

  quantity_delta NUMERIC(15,3) NOT NULL,

  unit_cost NUMERIC(15,2),

  reason VARCHAR(30) NOT NULL,

  reference_type VARCHAR(50),
  reference_id BIGINT,

  notes TEXT,

  created_by BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE INDEX IF NOT EXISTS idx_stock_movements_company
  ON erp_stock_movements(ias_company_id);

CREATE INDEX IF NOT EXISTS idx_stock_movements_product
  ON erp_stock_movements(ias_company_id, product_id);


-- ------------------------------------------------------------
-- Stock transfers
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_stock_transfers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT NOT NULL,

  product_id BIGINT NOT NULL
    REFERENCES erp_products(id)
    ON DELETE CASCADE,

  product_sku VARCHAR(100) NOT NULL,
  product_name VARCHAR(255) NOT NULL,

  from_warehouse_id BIGINT NOT NULL
    REFERENCES erp_warehouses(id),

  from_warehouse_name VARCHAR(255) NOT NULL,

  to_warehouse_id BIGINT NOT NULL
    REFERENCES erp_warehouses(id),

  to_warehouse_name VARCHAR(255) NOT NULL,

  quantity NUMERIC(15,3) NOT NULL,

  status VARCHAR(20) NOT NULL DEFAULT 'COMPLETED',

  created_by BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CHECK (quantity > 0),
  CHECK (from_warehouse_id <> to_warehouse_id)
);


-- ------------------------------------------------------------
-- Inventory permissions
-- ------------------------------------------------------------

-- These are seeded later in 010_seed_permissions.sql