-- ============================================================
-- 004_crm.sql
-- Customers, suppliers and contacts
-- ============================================================


-- ------------------------------------------------------------
-- Contacts
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT NOT NULL,

  contact_type VARCHAR(20) NOT NULL DEFAULT 'CUSTOMER',

  name VARCHAR(255) NOT NULL,
  phone VARCHAR(50),
  email VARCHAR(255),
  address TEXT,
  tax_id VARCHAR(100),

  credit_limit NUMERIC(15,2) NOT NULL DEFAULT 0,

  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CHECK (contact_type IN ('CUSTOMER', 'SUPPLIER', 'BOTH')),
  CHECK (credit_limit >= 0),

  -- Tenant-scoped uniqueness
  UNIQUE (ias_company_id, name, contact_type),

  -- Required as target for tenant-aware composite FKs
  UNIQUE (ias_company_id, id)
);


CREATE INDEX IF NOT EXISTS idx_contacts_company
  ON erp_contacts(ias_company_id);


-- ------------------------------------------------------------
-- Contact interactions
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_contact_interactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT NOT NULL,

  contact_id BIGINT NOT NULL,

  interaction_type VARCHAR(30) NOT NULL,

  notes TEXT,

  occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  created_by BIGINT NOT NULL,

  -- Contact must belong to the same company
  CONSTRAINT fk_contact_interactions_contact
    FOREIGN KEY (ias_company_id, contact_id)
    REFERENCES erp_contacts (ias_company_id, id)
    ON DELETE CASCADE
);


CREATE INDEX IF NOT EXISTS idx_contact_interactions_company
  ON erp_contact_interactions(ias_company_id);

CREATE INDEX IF NOT EXISTS idx_contact_interactions_contact
  ON erp_contact_interactions(ias_company_id, contact_id);

CREATE INDEX IF NOT EXISTS idx_contact_interactions_occurred_at
  ON erp_contact_interactions(ias_company_id, occurred_at);