-- ============================================================
-- 005_sales.sql
-- Sales orders and sales order lines
-- ============================================================


CREATE TABLE IF NOT EXISTS erp_sales_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT NOT NULL,

  order_number VARCHAR(50) NOT NULL,

  customer_id BIGINT NOT NULL
    REFERENCES erp_contacts(id),

  warehouse_id BIGINT NOT NULL
    REFERENCES erp_warehouses(id),

  warehouse_name VARCHAR(255) NOT NULL,

  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',

  order_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  currency VARCHAR(10) NOT NULL DEFAULT 'KES',

  subtotal NUMERIC(15,2) NOT NULL DEFAULT 0,
  discount_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
  tax_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
  total_amount NUMERIC(15,2) NOT NULL DEFAULT 0,

  notes TEXT,

  created_by BIGINT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (ias_company_id, order_number)
);


CREATE INDEX IF NOT EXISTS idx_sales_orders_company_status
  ON erp_sales_orders(ias_company_id, status);


-- ------------------------------------------------------------
-- Sales order items
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_sales_order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  sales_order_id BIGINT NOT NULL
    REFERENCES erp_sales_orders(id)
    ON DELETE CASCADE,

  product_id BIGINT NOT NULL
    REFERENCES erp_products(id),

  product_sku VARCHAR(100) NOT NULL,
  product_name VARCHAR(255) NOT NULL,

  warehouse_id BIGINT NOT NULL
    REFERENCES erp_warehouses(id),

  warehouse_name VARCHAR(255) NOT NULL,

  quantity NUMERIC(15,3) NOT NULL,

  unit_price NUMERIC(15,2) NOT NULL,

  discount_amount NUMERIC(15,2) NOT NULL DEFAULT 0,

  tax_rate NUMERIC(7,4) NOT NULL DEFAULT 0,

  line_total NUMERIC(15,2) NOT NULL,

  CHECK (quantity > 0)
);


CREATE INDEX IF NOT EXISTS idx_sales_items_order
  ON erp_sales_order_items(sales_order_id);