-- ============================================================
-- 005_sales.sql
-- Sales orders and sales order lines
-- ============================================================


-- ------------------------------------------------------------
-- Sales orders
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_sales_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT NOT NULL,

  order_number VARCHAR(50) NOT NULL,

  customer_id BIGINT NOT NULL,

  warehouse_id BIGINT NOT NULL,

  warehouse_name VARCHAR(255) NOT NULL,

  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',

  order_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  currency VARCHAR(10) NOT NULL DEFAULT 'KES',

  subtotal NUMERIC(15,2) NOT NULL DEFAULT 0,
  discount_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
  tax_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
  total_amount NUMERIC(15,2) NOT NULL DEFAULT 0,

  notes TEXT,

  created_by BIGINT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Tenant-scoped order number
  UNIQUE (ias_company_id, order_number),

  -- Required for tenant-aware child FKs
  UNIQUE (ias_company_id, id),

  -- Customer must belong to the same company
  CONSTRAINT fk_sales_orders_customer
    FOREIGN KEY (ias_company_id, customer_id)
    REFERENCES erp_contacts (ias_company_id, id)
    ON DELETE RESTRICT,

  -- Warehouse must belong to the same company
  CONSTRAINT fk_sales_orders_warehouse
    FOREIGN KEY (ias_company_id, warehouse_id)
    REFERENCES erp_warehouses (ias_company_id, id)
    ON DELETE RESTRICT,

  CHECK (subtotal >= 0),
  CHECK (discount_amount >= 0),
  CHECK (tax_amount >= 0),
  CHECK (total_amount >= 0)
);


CREATE INDEX IF NOT EXISTS idx_sales_orders_company
  ON erp_sales_orders(ias_company_id);

CREATE INDEX IF NOT EXISTS idx_sales_orders_company_status
  ON erp_sales_orders(ias_company_id, status);

CREATE INDEX IF NOT EXISTS idx_sales_orders_customer
  ON erp_sales_orders(ias_company_id, customer_id);

CREATE INDEX IF NOT EXISTS idx_sales_orders_warehouse
  ON erp_sales_orders(ias_company_id, warehouse_id);

CREATE INDEX IF NOT EXISTS idx_sales_orders_date
  ON erp_sales_orders(ias_company_id, order_date);


-- ------------------------------------------------------------
-- Sales order items
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_sales_order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT NOT NULL,

  sales_order_id BIGINT NOT NULL,

  product_id BIGINT NOT NULL,

  product_sku VARCHAR(100) NOT NULL,
  product_name VARCHAR(255) NOT NULL,

  warehouse_id BIGINT NOT NULL,

  warehouse_name VARCHAR(255) NOT NULL,

  quantity NUMERIC(15,3) NOT NULL,

  unit_price NUMERIC(15,2) NOT NULL,

  discount_amount NUMERIC(15,2) NOT NULL DEFAULT 0,

  tax_rate NUMERIC(7,4) NOT NULL DEFAULT 0,

  line_total NUMERIC(15,2) NOT NULL,

  -- Sales order must belong to the same company
  CONSTRAINT fk_sales_items_order
    FOREIGN KEY (ias_company_id, sales_order_id)
    REFERENCES erp_sales_orders (ias_company_id, id)
    ON DELETE CASCADE,

  -- Product must belong to the same company
  CONSTRAINT fk_sales_items_product
    FOREIGN KEY (ias_company_id, product_id)
    REFERENCES erp_products (ias_company_id, id)
    ON DELETE RESTRICT,

  -- Warehouse must belong to the same company
  CONSTRAINT fk_sales_items_warehouse
    FOREIGN KEY (ias_company_id, warehouse_id)
    REFERENCES erp_warehouses (ias_company_id, id)
    ON DELETE RESTRICT,

  CHECK (quantity > 0),
  CHECK (unit_price >= 0),
  CHECK (discount_amount >= 0),
  CHECK (tax_rate >= 0),
  CHECK (line_total >= 0)
);


CREATE INDEX IF NOT EXISTS idx_sales_items_company
  ON erp_sales_order_items(ias_company_id);

CREATE INDEX IF NOT EXISTS idx_sales_items_order
  ON erp_sales_order_items(ias_company_id, sales_order_id);

CREATE INDEX IF NOT EXISTS idx_sales_items_product
  ON erp_sales_order_items(ias_company_id, product_id);

CREATE INDEX IF NOT EXISTS idx_sales_items_warehouse
  ON erp_sales_order_items(ias_company_id, warehouse_id);