-- ============================================================
-- 006_purchasing.sql
-- Purchase orders and purchase order lines
-- ============================================================


CREATE TABLE IF NOT EXISTS erp_purchase_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ias_company_id BIGINT NOT NULL,
  po_number VARCHAR(50) NOT NULL,
  supplier_id BIGINT NOT NULL
    REFERENCES erp_contacts(id),
  warehouse_id BIGINT NOT NULL
    REFERENCES erp_warehouses(id),
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  order_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expected_date DATE,
  currency VARCHAR(10) NOT NULL DEFAULT 'KES',
  subtotal NUMERIC(15,2) NOT NULL DEFAULT 0,
  tax_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
  total_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
  notes TEXT,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (ias_company_id, po_number)
);


CREATE INDEX IF NOT EXISTS idx_po_company_status
  ON erp_purchase_orders(ias_company_id, status);


-- ------------------------------------------------------------
-- Purchase order items
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_purchase_order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  purchase_order_id BIGINT NOT NULL
    REFERENCES erp_purchase_orders(id)
    ON DELETE CASCADE,

  product_id BIGINT NOT NULL
    REFERENCES erp_products(id),

  product_sku VARCHAR(100) NOT NULL,
  product_name VARCHAR(255) NOT NULL,

  quantity NUMERIC(15,3) NOT NULL,

  received_quantity NUMERIC(15,3) NOT NULL DEFAULT 0,

  unit_cost NUMERIC(15,2) NOT NULL,

  tax_rate NUMERIC(7,4) NOT NULL DEFAULT 0,

  line_total NUMERIC(15,2) NOT NULL,

  CHECK (quantity > 0),
  CHECK (received_quantity >= 0)
);