-- ============================================================
-- 006_purchasing.sql
-- Purchase orders and purchase order lines
-- ============================================================


-- ------------------------------------------------------------
-- Purchase orders
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_purchase_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT NOT NULL,

  po_number VARCHAR(50) NOT NULL,

  supplier_id BIGINT NOT NULL,

  warehouse_id BIGINT NOT NULL,

  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',

  order_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  expected_date DATE,

  currency VARCHAR(10) NOT NULL DEFAULT 'KES',

  subtotal NUMERIC(15,2) NOT NULL DEFAULT 0,

  tax_amount NUMERIC(15,2) NOT NULL DEFAULT 0,

  total_amount NUMERIC(15,2) NOT NULL DEFAULT 0,

  notes TEXT,

  created_by BIGINT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Tenant-scoped PO number
  UNIQUE (ias_company_id, po_number),

  -- Required for tenant-aware child FKs
  UNIQUE (ias_company_id, id),

  -- Supplier must belong to the same company
  CONSTRAINT fk_purchase_orders_supplier
    FOREIGN KEY (ias_company_id, supplier_id)
    REFERENCES erp_contacts (ias_company_id, id)
    ON DELETE RESTRICT,

  -- Warehouse must belong to the same company
  CONSTRAINT fk_purchase_orders_warehouse
    FOREIGN KEY (ias_company_id, warehouse_id)
    REFERENCES erp_warehouses (ias_company_id, id)
    ON DELETE RESTRICT,

  CHECK (subtotal >= 0),
  CHECK (tax_amount >= 0),
  CHECK (total_amount >= 0),

  CHECK (
    expected_date IS NULL
    OR expected_date >= order_date::DATE
  )
);


CREATE INDEX IF NOT EXISTS idx_po_company
  ON erp_purchase_orders(ias_company_id);

CREATE INDEX IF NOT EXISTS idx_po_company_status
  ON erp_purchase_orders(ias_company_id, status);

CREATE INDEX IF NOT EXISTS idx_po_supplier
  ON erp_purchase_orders(ias_company_id, supplier_id);

CREATE INDEX IF NOT EXISTS idx_po_warehouse
  ON erp_purchase_orders(ias_company_id, warehouse_id);

CREATE INDEX IF NOT EXISTS idx_po_order_date
  ON erp_purchase_orders(ias_company_id, order_date);


-- ------------------------------------------------------------
-- Purchase order items
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_purchase_order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT NOT NULL,

  purchase_order_id BIGINT NOT NULL,

  product_id BIGINT NOT NULL,

  product_sku VARCHAR(100) NOT NULL,

  product_name VARCHAR(255) NOT NULL,

  quantity NUMERIC(15,3) NOT NULL,

  received_quantity NUMERIC(15,3) NOT NULL DEFAULT 0,

  unit_cost NUMERIC(15,2) NOT NULL,

  tax_rate NUMERIC(7,4) NOT NULL DEFAULT 0,

  line_total NUMERIC(15,2) NOT NULL,

  -- Purchase order must belong to the same company
  CONSTRAINT fk_purchase_items_order
    FOREIGN KEY (ias_company_id, purchase_order_id)
    REFERENCES erp_purchase_orders (ias_company_id, id)
    ON DELETE CASCADE,

  -- Product must belong to the same company
  CONSTRAINT fk_purchase_items_product
    FOREIGN KEY (ias_company_id, product_id)
    REFERENCES erp_products (ias_company_id, id)
    ON DELETE RESTRICT,

  CHECK (quantity > 0),

  CHECK (received_quantity >= 0),

  CHECK (received_quantity <= quantity),

  CHECK (unit_cost >= 0),

  CHECK (tax_rate >= 0),

  CHECK (line_total >= 0)
);


CREATE INDEX IF NOT EXISTS idx_purchase_items_company
  ON erp_purchase_order_items(ias_company_id);

CREATE INDEX IF NOT EXISTS idx_purchase_items_order
  ON erp_purchase_order_items(ias_company_id, purchase_order_id);

CREATE INDEX IF NOT EXISTS idx_purchase_items_product
  ON erp_purchase_order_items(ias_company_id, product_id);