-- ============================================================
-- 007_finance.sql
-- Accounts receivable, payments and journals
-- ============================================================


-- ------------------------------------------------------------
-- Invoices
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT NOT NULL,

  invoice_number VARCHAR(50) NOT NULL,

  customer_id BIGINT NOT NULL
    REFERENCES erp_contacts(id),

  sales_order_id BIGINT
    REFERENCES erp_sales_orders(id),

  status VARCHAR(20) NOT NULL DEFAULT 'OPEN',

  issue_date DATE NOT NULL DEFAULT CURRENT_DATE,
  due_date DATE,

  currency VARCHAR(10) NOT NULL DEFAULT 'KES',

  subtotal NUMERIC(15,2) NOT NULL DEFAULT 0,
  tax_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
  total_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
  paid_amount NUMERIC(15,2) NOT NULL DEFAULT 0,

  notes TEXT,

  created_by BIGINT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (ias_company_id, invoice_number),

  CHECK (total_amount >= 0),
  CHECK (paid_amount >= 0),
  CHECK (paid_amount <= total_amount)
);


CREATE INDEX IF NOT EXISTS idx_invoices_ar
  ON erp_invoices(ias_company_id, status, customer_id);


-- ------------------------------------------------------------
-- Invoice items
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_invoice_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  invoice_id BIGINT NOT NULL
    REFERENCES erp_invoices(id)
    ON DELETE CASCADE,

  product_id BIGINT
    REFERENCES erp_products(id),

  product_sku VARCHAR(100),
  product_name VARCHAR(255) NOT NULL,

  quantity NUMERIC(15,3) NOT NULL,

  unit_price NUMERIC(15,2) NOT NULL,

  tax_rate NUMERIC(7,4) NOT NULL DEFAULT 0,

  line_total NUMERIC(15,2) NOT NULL,

  CHECK (quantity > 0)
);


-- ------------------------------------------------------------
-- Payments
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT NOT NULL,

  customer_id BIGINT
    REFERENCES erp_contacts(id),

  payment_reference VARCHAR(100) NOT NULL,

  amount NUMERIC(15,2) NOT NULL,

  payment_date DATE NOT NULL DEFAULT CURRENT_DATE,

  method VARCHAR(30) NOT NULL DEFAULT 'CASH',

  notes TEXT,

  created_by BIGINT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (ias_company_id, payment_reference),

  CHECK (amount > 0)
);


-- ------------------------------------------------------------
-- Payment allocations
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_payment_allocations (
  payment_id BIGINT NOT NULL
    REFERENCES erp_payments(id)
    ON DELETE CASCADE,

  invoice_id BIGINT NOT NULL
    REFERENCES erp_invoices(id)
    ON DELETE CASCADE,

  amount NUMERIC(15,2) NOT NULL,

  PRIMARY KEY (payment_id, invoice_id),

  CHECK (amount > 0)
);


-- ------------------------------------------------------------
-- Journal entries
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_journal_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT NOT NULL,

  reference_type VARCHAR(50),
  reference_id BIGINT,

  description TEXT NOT NULL,

  entry_date DATE NOT NULL DEFAULT CURRENT_DATE,

  created_by BIGINT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ------------------------------------------------------------
-- Journal lines
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_journal_lines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  journal_entry_id BIGINT NOT NULL
    REFERENCES erp_journal_entries(id)
    ON DELETE CASCADE,

  account_code VARCHAR(50) NOT NULL,

  debit NUMERIC(15,2) NOT NULL DEFAULT 0,
  credit NUMERIC(15,2) NOT NULL DEFAULT 0,

  CHECK (debit >= 0),
  CHECK (credit >= 0),
  CHECK (
    (debit > 0 AND credit = 0)
    OR
    (credit > 0 AND debit = 0)
  )
);