-- ============================================================
-- 007_finance.sql
-- Accounts receivable, payments and journals
-- ============================================================


-- ------------------------------------------------------------
-- Invoices
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT NOT NULL,

  invoice_number VARCHAR(50) NOT NULL,

  customer_id BIGINT NOT NULL,

  sales_order_id BIGINT,

  status VARCHAR(20) NOT NULL DEFAULT 'OPEN',

  issue_date DATE NOT NULL DEFAULT CURRENT_DATE,
  due_date DATE,

  currency VARCHAR(10) NOT NULL DEFAULT 'KES',

  subtotal NUMERIC(15,2) NOT NULL DEFAULT 0,
  tax_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
  total_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
  paid_amount NUMERIC(15,2) NOT NULL DEFAULT 0,

  notes TEXT,

  created_by BIGINT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Tenant-scoped invoice number
  UNIQUE (ias_company_id, invoice_number),

  -- Required for tenant-aware child FKs
  UNIQUE (ias_company_id, id),

  -- Customer must belong to same company
  CONSTRAINT fk_invoices_customer
    FOREIGN KEY (ias_company_id, customer_id)
    REFERENCES erp_contacts (ias_company_id, id)
    ON DELETE RESTRICT,

  -- Sales order must belong to same company
  CONSTRAINT fk_invoices_sales_order
    FOREIGN KEY (ias_company_id, sales_order_id)
    REFERENCES erp_sales_orders (ias_company_id, id)
    ON DELETE SET NULL,

  CHECK (subtotal >= 0),
  CHECK (tax_amount >= 0),
  CHECK (total_amount >= 0),
  CHECK (paid_amount >= 0),
  CHECK (paid_amount <= total_amount),

  CHECK (
    due_date IS NULL
    OR due_date >= issue_date
  )
);


CREATE INDEX IF NOT EXISTS idx_invoices_company
  ON erp_invoices(ias_company_id);

CREATE INDEX IF NOT EXISTS idx_invoices_ar
  ON erp_invoices(ias_company_id, status, customer_id);

CREATE INDEX IF NOT EXISTS idx_invoices_sales_order
  ON erp_invoices(ias_company_id, sales_order_id);

CREATE INDEX IF NOT EXISTS idx_invoices_due_date
  ON erp_invoices(ias_company_id, due_date);


-- ------------------------------------------------------------
-- Invoice items
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_invoice_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT NOT NULL,

  invoice_id BIGINT NOT NULL,

  product_id BIGINT,

  product_sku VARCHAR(100),
  product_name VARCHAR(255) NOT NULL,

  quantity NUMERIC(15,3) NOT NULL,

  unit_price NUMERIC(15,2) NOT NULL,

  tax_rate NUMERIC(7,4) NOT NULL DEFAULT 0,

  line_total NUMERIC(15,2) NOT NULL,

  -- Invoice must belong to same company
  CONSTRAINT fk_invoice_items_invoice
    FOREIGN KEY (ias_company_id, invoice_id)
    REFERENCES erp_invoices (ias_company_id, id)
    ON DELETE CASCADE,

  -- Product, when present, must belong to same company
  CONSTRAINT fk_invoice_items_product
    FOREIGN KEY (ias_company_id, product_id)
    REFERENCES erp_products (ias_company_id, id)
    ON DELETE RESTRICT,

  CHECK (quantity > 0),
  CHECK (unit_price >= 0),
  CHECK (tax_rate >= 0),
  CHECK (line_total >= 0)
);


CREATE INDEX IF NOT EXISTS idx_invoice_items_company
  ON erp_invoice_items(ias_company_id);

CREATE INDEX IF NOT EXISTS idx_invoice_items_invoice
  ON erp_invoice_items(ias_company_id, invoice_id);

CREATE INDEX IF NOT EXISTS idx_invoice_items_product
  ON erp_invoice_items(ias_company_id, product_id);


-- ------------------------------------------------------------
-- Payments
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT NOT NULL,

  customer_id BIGINT,

  payment_reference VARCHAR(100) NOT NULL,

  amount NUMERIC(15,2) NOT NULL,

  payment_date DATE NOT NULL DEFAULT CURRENT_DATE,

  method VARCHAR(30) NOT NULL DEFAULT 'CASH',

  notes TEXT,

  created_by BIGINT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Tenant-scoped payment reference
  UNIQUE (ias_company_id, payment_reference),

  -- Required for tenant-aware payment allocation FK
  UNIQUE (ias_company_id, id),

  -- Customer, when provided, must belong to same company
  CONSTRAINT fk_payments_customer
    FOREIGN KEY (ias_company_id, customer_id)
    REFERENCES erp_contacts (ias_company_id, id)
    ON DELETE RESTRICT,

  CHECK (amount > 0)
);


CREATE INDEX IF NOT EXISTS idx_payments_company
  ON erp_payments(ias_company_id);

CREATE INDEX IF NOT EXISTS idx_payments_customer
  ON erp_payments(ias_company_id, customer_id);

CREATE INDEX IF NOT EXISTS idx_payments_date
  ON erp_payments(ias_company_id, payment_date);


-- ------------------------------------------------------------
-- Payment allocations
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_payment_allocations (
  ias_company_id BIGINT NOT NULL,

  payment_id BIGINT NOT NULL,

  invoice_id BIGINT NOT NULL,

  amount NUMERIC(15,2) NOT NULL,

  PRIMARY KEY (ias_company_id, payment_id, invoice_id),

  -- Payment must belong to same company
  CONSTRAINT fk_payment_allocations_payment
    FOREIGN KEY (ias_company_id, payment_id)
    REFERENCES erp_payments (ias_company_id, id)
    ON DELETE CASCADE,

  -- Invoice must belong to same company
  CONSTRAINT fk_payment_allocations_invoice
    FOREIGN KEY (ias_company_id, invoice_id)
    REFERENCES erp_invoices (ias_company_id, id)
    ON DELETE CASCADE,

  CHECK (amount > 0)
);


CREATE INDEX IF NOT EXISTS idx_payment_allocations_company
  ON erp_payment_allocations(ias_company_id);

CREATE INDEX IF NOT EXISTS idx_payment_allocations_payment
  ON erp_payment_allocations(ias_company_id, payment_id);

CREATE INDEX IF NOT EXISTS idx_payment_allocations_invoice
  ON erp_payment_allocations(ias_company_id, invoice_id);


-- ------------------------------------------------------------
-- Journal entries
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_journal_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT NOT NULL,

  reference_type VARCHAR(50),

  reference_id BIGINT,

  description TEXT NOT NULL,

  entry_date DATE NOT NULL DEFAULT CURRENT_DATE,

  created_by BIGINT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Required for tenant-aware journal line FK
  UNIQUE (ias_company_id, id)
);


CREATE INDEX IF NOT EXISTS idx_journal_entries_company
  ON erp_journal_entries(ias_company_id);

CREATE INDEX IF NOT EXISTS idx_journal_entries_date
  ON erp_journal_entries(ias_company_id, entry_date);

CREATE INDEX IF NOT EXISTS idx_journal_entries_reference
  ON erp_journal_entries(
    ias_company_id,
    reference_type,
    reference_id
  );


-- ------------------------------------------------------------
-- Journal lines
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_journal_lines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT NOT NULL,

  journal_entry_id BIGINT NOT NULL,

  account_code VARCHAR(50) NOT NULL,

  debit NUMERIC(15,2) NOT NULL DEFAULT 0,

  credit NUMERIC(15,2) NOT NULL DEFAULT 0,

  -- Journal entry must belong to same company
  CONSTRAINT fk_journal_lines_entry
    FOREIGN KEY (ias_company_id, journal_entry_id)
    REFERENCES erp_journal_entries (ias_company_id, id)
    ON DELETE CASCADE,

  CHECK (debit >= 0),
  CHECK (credit >= 0),

  CHECK (
    (debit > 0 AND credit = 0)
    OR
    (credit > 0 AND debit = 0)
  )
);


CREATE INDEX IF NOT EXISTS idx_journal_lines_company
  ON erp_journal_lines(ias_company_id);

CREATE INDEX IF NOT EXISTS idx_journal_lines_entry
  ON erp_journal_lines(ias_company_id, journal_entry_id);

CREATE INDEX IF NOT EXISTS idx_journal_lines_account
  ON erp_journal_lines(ias_company_id, account_code);