-- ============================================================
-- 008_hr.sql
-- Human Resources
-- ============================================================


-- ------------------------------------------------------------
-- Departments
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_departments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT NOT NULL,

  name VARCHAR(150) NOT NULL,
  code VARCHAR(50) NOT NULL,

  description TEXT,

  is_active BOOLEAN NOT NULL DEFAULT TRUE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (ias_company_id, id),
  UNIQUE (ias_company_id, code),
  UNIQUE (ias_company_id, name)
);


CREATE INDEX IF NOT EXISTS idx_departments_company
  ON erp_departments(ias_company_id);


-- ------------------------------------------------------------
-- Job titles
--
-- IMPORTANT:
-- Job title is an HR position, NOT an ERP permission role.
--
-- Example:
--   Job title: Senior Accountant
--   ERP role:  FINANCE_ADMIN
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_job_titles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT NOT NULL,

  name VARCHAR(150) NOT NULL,
  code VARCHAR(50) NOT NULL,

  description TEXT,

  is_active BOOLEAN NOT NULL DEFAULT TRUE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (ias_company_id, id),
  UNIQUE (ias_company_id, code),
  UNIQUE (ias_company_id, name)
);


CREATE INDEX IF NOT EXISTS idx_job_titles_company
  ON erp_job_titles(ias_company_id);


-- ------------------------------------------------------------
-- Employees
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_employees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT NOT NULL,

  employee_number VARCHAR(50) NOT NULL,

  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,

  email VARCHAR(255),
  phone VARCHAR(50),

  department_id BIGINT,
  department_name VARCHAR(150),

  job_title_id BIGINT,
  job_title_name VARCHAR(150),

  hire_date DATE,

  salary NUMERIC(15,2) NOT NULL DEFAULT 0,

  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (ias_company_id, employee_number),

  -- Required for tenant-aware child FKs
  UNIQUE (ias_company_id, id),

  CONSTRAINT fk_employee_department
    FOREIGN KEY (ias_company_id, department_id)
    REFERENCES erp_departments(ias_company_id, id)
    ON DELETE SET NULL,

  CONSTRAINT fk_employee_job_title
    FOREIGN KEY (ias_company_id, job_title_id)
    REFERENCES erp_job_titles(ias_company_id, id)
    ON DELETE SET NULL,

  CHECK (salary >= 0)
);


CREATE INDEX IF NOT EXISTS idx_employees_company
  ON erp_employees(ias_company_id);

CREATE INDEX IF NOT EXISTS idx_employees_department
  ON erp_employees(ias_company_id, department_id);

CREATE INDEX IF NOT EXISTS idx_employees_job_title
  ON erp_employees(ias_company_id, job_title_id);


-- ------------------------------------------------------------
-- Attendance
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT NOT NULL,

  employee_id BIGINT NOT NULL,

  attendance_date DATE NOT NULL,

  clock_in TIMESTAMPTZ,

  clock_out TIMESTAMPTZ,

  notes TEXT,

  -- One attendance record per employee per day per company
  UNIQUE (
    ias_company_id,
    employee_id,
    attendance_date
  ),

  CONSTRAINT fk_attendance_employee
    FOREIGN KEY (ias_company_id, employee_id)
    REFERENCES erp_employees(ias_company_id, id)
    ON DELETE CASCADE,

  CHECK (
    clock_out IS NULL
    OR clock_in IS NULL
    OR clock_out >= clock_in
  )
);


CREATE INDEX IF NOT EXISTS idx_attendance_employee
  ON erp_attendance(
    ias_company_id,
    employee_id,
    attendance_date
  );

CREATE INDEX IF NOT EXISTS idx_attendance_date
  ON erp_attendance(
    ias_company_id,
    attendance_date
  );


-- ------------------------------------------------------------
-- Leave requests
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_leave_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT NOT NULL,

  employee_id BIGINT NOT NULL,

  leave_type VARCHAR(50) NOT NULL,

  starts_on DATE NOT NULL,

  ends_on DATE NOT NULL,

  reason TEXT,

  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',

  approved_by BIGINT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_leave_requests_employee
    FOREIGN KEY (ias_company_id, employee_id)
    REFERENCES erp_employees(ias_company_id, id)
    ON DELETE CASCADE,

  CHECK (ends_on >= starts_on)
);


CREATE INDEX IF NOT EXISTS idx_leave_employee
  ON erp_leave_requests(
    ias_company_id,
    employee_id,
    starts_on
  );

CREATE INDEX IF NOT EXISTS idx_leave_company_status
  ON erp_leave_requests(
    ias_company_id,
    status
  );

CREATE INDEX IF NOT EXISTS idx_leave_dates
  ON erp_leave_requests(
    ias_company_id,
    starts_on,
    ends_on
  );


-- ------------------------------------------------------------
-- Payroll runs
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_payroll_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT NOT NULL,

  period_start DATE NOT NULL,

  period_end DATE NOT NULL,

  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',

  total_gross NUMERIC(15,2) NOT NULL DEFAULT 0,

  total_deductions NUMERIC(15,2) NOT NULL DEFAULT 0,

  total_net NUMERIC(15,2) NOT NULL DEFAULT 0,

  created_by BIGINT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (
    ias_company_id,
    period_start,
    period_end
  ),

  -- Required for tenant-aware payroll item FK
  UNIQUE (ias_company_id, id),

  CHECK (period_end >= period_start),

  CHECK (total_gross >= 0),

  CHECK (total_deductions >= 0),

  CHECK (total_net >= 0)
);


CREATE INDEX IF NOT EXISTS idx_payroll_runs_company
  ON erp_payroll_runs(ias_company_id);

CREATE INDEX IF NOT EXISTS idx_payroll_runs_status
  ON erp_payroll_runs(ias_company_id, status);

CREATE INDEX IF NOT EXISTS idx_payroll_runs_period
  ON erp_payroll_runs(
    ias_company_id,
    period_start,
    period_end
  );


-- ------------------------------------------------------------
-- Payroll items
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_payroll_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT NOT NULL,

  payroll_run_id BIGINT NOT NULL,

  employee_id BIGINT NOT NULL,

  gross NUMERIC(15,2) NOT NULL,

  deductions NUMERIC(15,2) NOT NULL DEFAULT 0,

  net NUMERIC(15,2) NOT NULL,

  CONSTRAINT fk_payroll_items_run
    FOREIGN KEY (ias_company_id, payroll_run_id)
    REFERENCES erp_payroll_runs(ias_company_id, id)
    ON DELETE CASCADE,

  CONSTRAINT fk_payroll_items_employee
    FOREIGN KEY (ias_company_id, employee_id)
    REFERENCES erp_employees(ias_company_id, id)
    ON DELETE RESTRICT,

  CHECK (gross >= 0),

  CHECK (deductions >= 0),

  CHECK (net >= 0),

  CHECK (deductions <= gross),

  CHECK (net = gross - deductions)
);


CREATE INDEX IF NOT EXISTS idx_payroll_items_company
  ON erp_payroll_items(ias_company_id);

CREATE INDEX IF NOT EXISTS idx_payroll_items_run
  ON erp_payroll_items(
    ias_company_id,
    payroll_run_id
  );

CREATE INDEX IF NOT EXISTS idx_payroll_items_employee
  ON erp_payroll_items(
    ias_company_id,
    employee_id
  );