-- ============================================================
-- 009_workflow.sql
-- Notifications, workflow rules and approval requests
-- ============================================================


-- ------------------------------------------------------------
-- Notifications
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT NOT NULL,

  ias_user_id BIGINT,

  type VARCHAR(50) NOT NULL,

  title VARCHAR(255) NOT NULL,

  message TEXT NOT NULL,

  entity_type VARCHAR(50),
  entity_id BIGINT,

  is_read BOOLEAN NOT NULL DEFAULT FALSE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE INDEX IF NOT EXISTS idx_notifications_user
  ON erp_notifications(
    ias_company_id,
    ias_user_id,
    is_read
  );


-- ------------------------------------------------------------
-- Workflow rules
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_workflow_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT NOT NULL,

  name VARCHAR(255) NOT NULL,

  event_type VARCHAR(100) NOT NULL,

  threshold_amount NUMERIC(15,2),

  action_type VARCHAR(50) NOT NULL DEFAULT 'NOTIFY',

  target_user_id BIGINT,

  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

  created_by BIGINT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ------------------------------------------------------------
-- Approval requests
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_approval_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ias_company_id BIGINT NOT NULL,

  module VARCHAR(50) NOT NULL,

  entity_type VARCHAR(50) NOT NULL,

  entity_id BIGINT NOT NULL,

  requested_by BIGINT NOT NULL,

  assigned_to BIGINT,

  amount NUMERIC(15,2),

  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',

  decided_by BIGINT,
  decided_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE INDEX IF NOT EXISTS idx_approval_requests_company
  ON erp_approval_requests(
    ias_company_id,
    status
  );