-- ============================================================
-- 009_workflow.sql
-- Notifications, workflow rules and approval requests
-- ============================================================


-- ------------------------------------------------------------
-- Notifications
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Tenant
  ias_company_id BIGINT NOT NULL,

  -- IAS user who receives the notification.
  -- No local FK because users are owned by IAS.
  ias_user_id BIGINT,

  type VARCHAR(50) NOT NULL,

  title VARCHAR(255) NOT NULL,

  message TEXT NOT NULL,

  -- Polymorphic reference to the ERP entity that triggered
  -- the notification, e.g. SALES_ORDER, PURCHASE_ORDER, INVOICE.
  entity_type VARCHAR(50),
  entity_id BIGINT,

  is_read BOOLEAN NOT NULL DEFAULT FALSE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Allows this table to be safely referenced by a future
  -- company-scoped composite FK.
  CONSTRAINT uq_notifications_company_id
    UNIQUE (ias_company_id, id)
);


CREATE INDEX IF NOT EXISTS idx_notifications_user
  ON erp_notifications (
    ias_company_id,
    ias_user_id,
    is_read
  );


CREATE INDEX IF NOT EXISTS idx_notifications_company_created
  ON erp_notifications (
    ias_company_id,
    created_at DESC
  );


CREATE INDEX IF NOT EXISTS idx_notifications_entity
  ON erp_notifications (
    ias_company_id,
    entity_type,
    entity_id
  );


-- ------------------------------------------------------------
-- Workflow rules
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_workflow_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Tenant
  ias_company_id BIGINT NOT NULL,

  name VARCHAR(255) NOT NULL,

  event_type VARCHAR(100) NOT NULL,

  threshold_amount NUMERIC(15,2),

  action_type VARCHAR(50) NOT NULL DEFAULT 'NOTIFY',

  -- IAS user ID.
  -- No local FK because users are owned by IAS.
  target_user_id BIGINT,

  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

  -- IAS user ID who created the rule.
  created_by BIGINT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Allows safe company-scoped references from future tables.
  CONSTRAINT uq_workflow_rules_company_id
    UNIQUE (ias_company_id, id),

  CONSTRAINT chk_workflow_threshold_amount
    CHECK (
      threshold_amount IS NULL
      OR threshold_amount >= 0
    ),

  CONSTRAINT chk_workflow_action_type
    CHECK (
      action_type IN (
        'NOTIFY',
        'CREATE_APPROVAL'
      )
    ),

  CONSTRAINT chk_workflow_status
    CHECK (
      status IN (
        'ACTIVE',
        'INACTIVE'
      )
    )
);


CREATE INDEX IF NOT EXISTS idx_workflow_rules_company
  ON erp_workflow_rules (
    ias_company_id
  );


CREATE INDEX IF NOT EXISTS idx_workflow_rules_event
  ON erp_workflow_rules (
    ias_company_id,
    event_type,
    status
  );


CREATE INDEX IF NOT EXISTS idx_workflow_rules_target_user
  ON erp_workflow_rules (
    ias_company_id,
    target_user_id,
    status
  );


-- ------------------------------------------------------------
-- Approval requests
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS erp_approval_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Tenant
  ias_company_id BIGINT NOT NULL,

  module VARCHAR(50) NOT NULL,

  -- Polymorphic entity reference.
  -- Examples:
  --   SALES_ORDER
  --   PURCHASE_ORDER
  --   INVOICE
  --   STOCK_TRANSFER
  --   LEAVE_REQUEST
  entity_type VARCHAR(50) NOT NULL,

  entity_id BIGINT NOT NULL,

  -- IAS user who requested approval.
  requested_by BIGINT NOT NULL,

  -- IAS user assigned to approve.
  assigned_to BIGINT,

  amount NUMERIC(15,2),

  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',

  -- IAS user who made the decision.
  decided_by BIGINT,

  decided_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Allows safe company-scoped references from future tables.
  CONSTRAINT uq_approval_requests_company_id
    UNIQUE (ias_company_id, id),

  CONSTRAINT chk_approval_amount
    CHECK (
      amount IS NULL
      OR amount >= 0
    ),

  CONSTRAINT chk_approval_status
    CHECK (
      status IN (
        'PENDING',
        'APPROVED',
        'REJECTED',
        'CANCELLED'
      )
    ),

  CONSTRAINT chk_approval_decision
    CHECK (
      (
        status = 'PENDING'
        AND decided_at IS NULL
      )
      OR
      (
        status IN ('APPROVED', 'REJECTED')
        AND decided_at IS NOT NULL
      )
      OR
      (
        status = 'CANCELLED'
      )
    )
);


CREATE INDEX IF NOT EXISTS idx_approval_requests_company
  ON erp_approval_requests (
    ias_company_id,
    status
  );


CREATE INDEX IF NOT EXISTS idx_approval_requests_assigned
  ON erp_approval_requests (
    ias_company_id,
    assigned_to,
    status
  );


CREATE INDEX IF NOT EXISTS idx_approval_requests_requested_by
  ON erp_approval_requests (
    ias_company_id,
    requested_by,
    created_at DESC
  );


CREATE INDEX IF NOT EXISTS idx_approval_requests_entity
  ON erp_approval_requests (
    ias_company_id,
    module,
    entity_type,
    entity_id
  );


CREATE INDEX IF NOT EXISTS idx_approval_requests_created
  ON erp_approval_requests (
    ias_company_id,
    created_at DESC
  );