-- ============================================================
-- 011_supplier_payables.sql
-- Accounts payable, supplier bills and supplier payments
-- ============================================================

INSERT INTO erp_permissions (module, action)
VALUES ('finance', 'manage_payables'), ('finance', 'post_supplier_payment')
ON CONFLICT (module, action) DO NOTHING;

CREATE TABLE IF NOT EXISTS erp_supplier_bills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ias_company_id BIGINT NOT NULL,
  bill_number VARCHAR(100) NOT NULL,
  supplier_id BIGINT NOT NULL,
  purchase_order_id BIGINT,
  status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
  issue_date DATE NOT NULL DEFAULT CURRENT_DATE,
  due_date DATE,
  currency VARCHAR(10) NOT NULL DEFAULT 'KES',
  subtotal NUMERIC(15,2) NOT NULL DEFAULT 0,
  tax_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
  total_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
  paid_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
  notes TEXT,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (ias_company_id, bill_number),
  UNIQUE (ias_company_id, id),
  CONSTRAINT fk_supplier_bills_supplier FOREIGN KEY (ias_company_id, supplier_id)
    REFERENCES erp_contacts (ias_company_id, id) ON DELETE RESTRICT,
  CONSTRAINT fk_supplier_bills_order FOREIGN KEY (ias_company_id, purchase_order_id)
    REFERENCES erp_purchase_orders (ias_company_id, id) ON DELETE SET NULL,
  CHECK (subtotal >= 0), CHECK (tax_amount >= 0), CHECK (total_amount >= 0),
  CHECK (paid_amount >= 0), CHECK (paid_amount <= total_amount),
  CHECK (due_date IS NULL OR due_date >= issue_date)
);

CREATE INDEX IF NOT EXISTS idx_supplier_bills_company_status
  ON erp_supplier_bills(ias_company_id, status);
CREATE INDEX IF NOT EXISTS idx_supplier_bills_supplier
  ON erp_supplier_bills(ias_company_id, supplier_id);

CREATE TABLE IF NOT EXISTS erp_supplier_bill_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ias_company_id BIGINT NOT NULL,
  supplier_bill_id BIGINT NOT NULL,
  product_id BIGINT,
  product_sku VARCHAR(100),
  product_name VARCHAR(255) NOT NULL,
  quantity NUMERIC(15,3) NOT NULL,
  unit_cost NUMERIC(15,2) NOT NULL,
  tax_rate NUMERIC(7,4) NOT NULL DEFAULT 0,
  line_total NUMERIC(15,2) NOT NULL,
  CONSTRAINT fk_supplier_bill_items_bill FOREIGN KEY (ias_company_id, supplier_bill_id)
    REFERENCES erp_supplier_bills (ias_company_id, id) ON DELETE CASCADE,
  CONSTRAINT fk_supplier_bill_items_product FOREIGN KEY (ias_company_id, product_id)
    REFERENCES erp_products (ias_company_id, id) ON DELETE RESTRICT,
  CHECK (quantity > 0), CHECK (unit_cost >= 0), CHECK (tax_rate >= 0), CHECK (line_total >= 0)
);

CREATE INDEX IF NOT EXISTS idx_supplier_bill_items_bill
  ON erp_supplier_bill_items(ias_company_id, supplier_bill_id);

CREATE TABLE IF NOT EXISTS erp_supplier_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ias_company_id BIGINT NOT NULL,
  supplier_id BIGINT,
  payment_reference VARCHAR(100) NOT NULL,
  amount NUMERIC(15,2) NOT NULL,
  payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
  method VARCHAR(30) NOT NULL DEFAULT 'CASH',
  notes TEXT,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (ias_company_id, payment_reference),
  UNIQUE (ias_company_id, id),
  CONSTRAINT fk_supplier_payments_supplier FOREIGN KEY (ias_company_id, supplier_id)
    REFERENCES erp_contacts (ias_company_id, id) ON DELETE RESTRICT,
  CHECK (amount > 0)
);

CREATE TABLE IF NOT EXISTS erp_supplier_payment_allocations (
  ias_company_id BIGINT NOT NULL,
  payment_id BIGINT NOT NULL,
  bill_id BIGINT NOT NULL,
  amount NUMERIC(15,2) NOT NULL,
  PRIMARY KEY (ias_company_id, payment_id, bill_id),
  CONSTRAINT fk_supplier_payment_allocations_payment FOREIGN KEY (ias_company_id, payment_id)
    REFERENCES erp_supplier_payments (ias_company_id, id) ON DELETE CASCADE,
  CONSTRAINT fk_supplier_payment_allocations_bill FOREIGN KEY (ias_company_id, bill_id)
    REFERENCES erp_supplier_bills (ias_company_id, id) ON DELETE CASCADE,
  CHECK (amount > 0)
);

CREATE INDEX IF NOT EXISTS idx_supplier_payment_allocations_bill
  ON erp_supplier_payment_allocations(ias_company_id, bill_id);