-- ============================================================
-- 012_report_delivery.sql
-- Scheduled report delivery: per-client subscriptions, pre-
-- computed snapshots, and a send log for email/WhatsApp reports.
-- ============================================================

CREATE TABLE IF NOT EXISTS erp_report_subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ias_company_id BIGINT NOT NULL,
  channel VARCHAR(20) NOT NULL,
  frequency VARCHAR(20) NOT NULL,
  day_of_week SMALLINT,
  time_of_day TIME NOT NULL DEFAULT '08:00',
  recipient VARCHAR(255) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (channel IN ('EMAIL', 'WHATSAPP')),
  CHECK (frequency IN ('DAILY', 'WEEKLY')),
  CHECK (frequency = 'DAILY' OR day_of_week IS NOT NULL),
  CHECK (day_of_week IS NULL OR day_of_week BETWEEN 0 AND 6)
);

CREATE INDEX IF NOT EXISTS idx_report_subscriptions_company
  ON erp_report_subscriptions(ias_company_id);
CREATE INDEX IF NOT EXISTS idx_report_subscriptions_due_lookup
  ON erp_report_subscriptions(enabled, frequency, time_of_day);

-- One row per company per period. `data` holds the pre-aggregated
-- metrics computed by the snapshot job; dispatch reads this instead of
-- querying live tables, so a report can be re-sent later without the
-- numbers drifting from what was actually sent.
CREATE TABLE IF NOT EXISTS erp_report_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ias_company_id BIGINT NOT NULL,
  period_type VARCHAR(20) NOT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  data JSONB NOT NULL,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (period_type IN ('DAILY', 'WEEKLY')),
  CHECK (period_end >= period_start),
  UNIQUE (ias_company_id, period_type, period_start)
);

CREATE INDEX IF NOT EXISTS idx_report_snapshots_lookup
  ON erp_report_snapshots(ias_company_id, period_type, period_end DESC);

CREATE TABLE IF NOT EXISTS erp_report_send_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscription_id BIGINT NOT NULL,
  snapshot_id BIGINT,
  status VARCHAR(20) NOT NULL,
  error_message TEXT,
  sent_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_send_logs_subscription FOREIGN KEY (subscription_id)
    REFERENCES erp_report_subscriptions (id) ON DELETE CASCADE,
  CONSTRAINT fk_send_logs_snapshot FOREIGN KEY (snapshot_id)
    REFERENCES erp_report_snapshots (id) ON DELETE SET NULL,
  CHECK (status IN ('SUCCESS', 'FAILED'))
);

CREATE INDEX IF NOT EXISTS idx_send_logs_subscription
  ON erp_report_send_logs(subscription_id, sent_at DESC);

INSERT INTO erp_permissions (module, action)
VALUES
  ('report-delivery', 'view'),
  ('report-delivery', 'manage')
ON CONFLICT DO NOTHING;
