-- ============================================================
-- 013_operating_expenses.sql
-- Non-inventory operating expenses and their journal entries
-- ============================================================

CREATE TABLE IF NOT EXISTS erp_operating_expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ias_company_id BIGINT NOT NULL,
  expense_number VARCHAR(100) NOT NULL,
  expense_date DATE NOT NULL DEFAULT CURRENT_DATE,
  category VARCHAR(100) NOT NULL,
  description TEXT NOT NULL,
  amount NUMERIC(15,2) NOT NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'KES',
  payment_method VARCHAR(30) NOT NULL DEFAULT 'CASH',
  payment_account_code VARCHAR(50) NOT NULL DEFAULT 'CASH',
  supplier_id BIGINT,
  reference VARCHAR(100),
  notes TEXT,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (ias_company_id, expense_number),
  UNIQUE (ias_company_id, id),
  CONSTRAINT fk_operating_expenses_supplier FOREIGN KEY (ias_company_id, supplier_id)
    REFERENCES erp_contacts (ias_company_id, id) ON DELETE RESTRICT,
  CHECK (amount > 0),
  CHECK (payment_method IN ('CASH', 'BANK', 'CREDIT'))
);

CREATE INDEX IF NOT EXISTS idx_operating_expenses_company_date
  ON erp_operating_expenses(ias_company_id, expense_date DESC);
CREATE INDEX IF NOT EXISTS idx_operating_expenses_category
  ON erp_operating_expenses(ias_company_id, category);

INSERT INTO erp_permissions (module, action)
VALUES ('finance', 'post_expense')
ON CONFLICT (module, action) DO NOTHING;
